name = "default_registry"
uuid = "959a66c5-bb29-4f2a-971a-bfe6a3ec51db"
repo = "https://github.com/Marchaser/LocalRegistry"
description = "My private registry"

[packages]
774e5fed-2ff0-4510-9b43-b9e61d55845f = { name = "NumericalRecipe", path = "N/NumericalRecipe" }
afe1064b-ec38-4da5-884a-4fdc6836ef55 = { name = "CoDoSol", path = "C/CoDoSol" }
